## พื้นฐานเกี่ยวกับ [Numpy library](http://www.numpy.org/) (Numerical Python)

มีความสามารถที่น่าสนใจดังนี้
* ndarray
* Mathematical function
* Linear algebra
* Randim number generation
* Fourier transform
* Reading and writing data


In [1]:
import numpy as np

### มาดูประสิทธิภาพการทำงานของ Numpy library กับ Standard Python

In [6]:
# Create with numpy
my_arr = np.arange(1000000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [8]:
# Create with standard python
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 20.8 ms, sys: 21.2 ms, total: 42 ms
Wall time: 40.6 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 803 ms, sys: 206 ms, total: 1.01 s
Wall time: 1.03 s


## The NumPy ndarray: A Multidimensional Array Object

In [10]:
data = np.random.randn(2, 3)
data

array([[-1.12505187,  0.68994896, -0.01696614],
       [-1.96637194, -0.75431095,  0.45606257]])

In [11]:
%time data * 10

CPU times: user 26 µs, sys: 7 µs, total: 33 µs
Wall time: 35 µs


array([[-11.25051866,   6.89948959,  -0.16966137],
       [-19.66371936,  -7.54310951,   4.56062568]])

In [13]:
%time data + 10

CPU times: user 28 µs, sys: 1 µs, total: 29 µs
Wall time: 34.1 µs


array([[  8.87494813,  10.68994896,   9.98303386],
       [  8.03362806,   9.24568905,  10.45606257]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

### Creating ndarrays

In [19]:
data1 = [6., 7.5, 8, 0, 1]
arr1 = np.array([data1,data1])
arr1

array([[ 6. ,  7.5,  8. ,  0. ,  1. ],
       [ 6. ,  7.5,  8. ,  0. ,  1. ]])

In [21]:
arr1.shape

(2, 5)

In [20]:
arr1.dtype

dtype('float64')